/**
 * Mesh every shell at every LOD and write the result into TypeScript.
 *
 *     npx tsx tools/bake.ts                 # all three LODs
 *     npx tsx tools/bake.ts --lod low       # one, for a fast loop iteration
 *     npx tsx tools/bake.ts --only body,hair
 *
 * Writes src/generated/lod_<name>.ts plus a bake report the review loop reads
 * to see which shells are empty, oversized, or throwing.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { compact, surfaceNets } from '../src/mesh/surfacenets.js';
import { encodeMesh } from '../src/mesh/encode.js';
import { EncodedLod, EncodedMesh } from '../src/mesh/format.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

// Fold the spec fragments in first: a part author's numbers must be live in the
// same command that meshes their shell, or they will chase a stale bake.
//
// The spec is then pulled in with a dynamic import, and that is not a style
// choice.  ES module imports are evaluated before any of this file's body runs,
// so a static `import ... from '../src/spec.js'` would read the *previous*
// resolved.json and the merge would only ever take effect on the following run.
execFileSync(process.execPath, ['--import', 'tsx', `${ROOT}/tools/merge_spec.ts`], { stdio: 'inherit' });

const { MATERIAL_NAMES, SPEC } = await import('../src/spec.js');
const { buildShellsDetailed } = await import('../src/scene.js');

const genDir = resolve(ROOT, arg('gen') ?? 'src/generated');
// The generated file imports its type from wherever it lands, which is not
// always src/generated -- part authors bake into their own directory so their
// runs do not clobber each other.
const formatImport = relative(genDir, `${ROOT}/src/mesh/format.js`).replace(/\\/g, '/');
const wantLods = (arg('lod') ?? 'high,medium,low').split(',').map((s) => s.trim());
const onlyRaw = arg('only');
const only = onlyRaw ? new Set(onlyRaw.split(',').map((s) => s.trim())) : null;

const report: Record<string, unknown> = { lods: {}, shells: {}, failures: [] };
const built = await buildShellsDetailed(undefined, only ?? undefined);
const shells = built.shells;
for (const f of built.failures) {
  console.error(`[bake] part "${f.part}" failed at ${f.stage}: ${f.message}`);
}
report.failures = built.failures;
if (shells.length === 0) {
  console.error('[bake] no shells to mesh -- every part returned empty');
}

mkdirSync(genDir, { recursive: true });

for (const lodName of wantLods) {
  const lod = (SPEC.lod as unknown as Record<string, { voxel: number }>)[lodName];
  if (!lod) {
    console.error(`[bake] unknown lod "${lodName}"`);
    continue;
  }
  const meshes: EncodedMesh[] = [];
  let totalTris = 0;
  let totalMs = 0;
  let totalBytes = 0;

  for (const shell of shells) {
    const voxel = lod.voxel * (shell.voxelScale ?? 1);
    const meshed = compact(surfaceNets(shell.field, { voxel, material: shell.material }));
    const enc = encodeMesh(shell.name, meshed, MATERIAL_NAMES);
    const bytes = enc.position.length + enc.normal.length + enc.index.length + enc.material.length;
    meshes.push(enc);
    totalTris += meshed.stats.triangles;
    totalMs += meshed.stats.ms;
    totalBytes += bytes;
    (report.shells as Record<string, unknown>)[`${lodName}/${shell.name}`] = {
      voxel: +voxel.toFixed(5),
      ...meshed.stats,
      kb: Math.round(bytes / 1024),
    };
    const skip = meshed.stats.blocksSkipped + meshed.stats.blocksSampled;
    console.log(
      `  ${lodName.padEnd(6)} ${shell.name.padEnd(14)} voxel ${(voxel * 1000).toFixed(1)}mm  ` +
      `tris ${String(meshed.stats.triangles).padStart(7)}  ` +
      `skip ${((100 * meshed.stats.blocksSkipped) / Math.max(1, skip)).toFixed(0)}%  ` +
      `${String(meshed.stats.ms).padStart(6)}ms  ${(bytes / 1024).toFixed(0)}kB`,
    );
    if (meshed.stats.triangles === 0) console.warn(`  [bake] ${shell.name} produced no geometry at ${lodName}`);
  }

  const payload: EncodedLod = { name: lodName, voxel: lod.voxel, meshes };
  const varName = `LOD_${lodName.toUpperCase()}`;
  writeFileSync(
    `${genDir}/lod_${lodName}.ts`,
    `// Generated by tools/bake.ts -- do not edit.\n` +
    `import type { EncodedLod } from '${formatImport}';\n\n` +
    `export const ${varName}: EncodedLod = ${JSON.stringify(payload)};\n`,
  );
  (report.lods as Record<string, unknown>)[lodName] = {
    triangles: totalTris, ms: totalMs, kb: Math.round(totalBytes / 1024), shells: meshes.length,
  };
  console.log(`[bake] ${lodName}: ${totalTris} tris, ${(totalBytes / 1024 / 1024).toFixed(2)} MB, ${(totalMs / 1000).toFixed(1)}s`);
}

// Export every LOD file present, not just the ones this invocation baked.
// `--lod low` is the normal fast loop, and rewriting the index to export only
// LOW makes the viewer's LOD switch look broken while lod_high.ts is sitting
// right there on disk.
const ORDER = ['high', 'medium', 'low'];
const present = readdirSync(genDir)
  .map((f) => /^lod_([a-z0-9]+)\.ts$/.exec(f)?.[1])
  .filter((n): n is string => Boolean(n))
  .sort((a, b) => (ORDER.indexOf(a) + 1 || 99) - (ORDER.indexOf(b) + 1 || 99));

writeFileSync(
  `${genDir}/index.ts`,
  `// Generated by tools/bake.ts -- do not edit.\n` +
  present.map((n) => `export { LOD_${n.toUpperCase()} } from './lod_${n}.js';\n`).join('') +
  `\nexport const BAKED_LODS = [${present.map((n) => `'${n}'`).join(', ')}] as const;\n`,
);
mkdirSync(`${ROOT}/out`, { recursive: true });
writeFileSync(`${ROOT}/out/bake_report${arg('gen') ? '_' + arg('gen')!.replace(/[^a-z0-9]+/gi, '_') : ''}.json`, JSON.stringify(report, null, 2));
console.log(`[bake] wrote ${genDir}`);
