/**
 * The spec, and the skeleton derived from it.
 *
 * spec/resolved.json is generated by tools/merge_spec.ts from spec/jinx.json
 * plus every fragment in spec/parts/, so authors working in parallel each own a
 * fragment instead of fighting over one file.
 *
 * Parts never hard-code a number: they read the spec and the joints resolved
 * here, so a review round can move a landmark in spec/jinx.json and every part
 * that hangs off it follows.  That is the whole reason the build is data-driven
 * -- a fix found by measuring a render has somewhere to land.
 */
import spec from '../spec/resolved.json' with { type: 'json' };
import { Vec3 } from './sdf/types.js';

export type Spec = typeof spec;
export const SPEC: Spec = spec as Spec;

export type JointName =
  | 'root' | 'hips' | 'waist' | 'chest' | 'neck' | 'head' | 'headTop'
  | 'shoulderL' | 'elbowL' | 'wristL' | 'handL'
  | 'shoulderR' | 'elbowR' | 'wristR' | 'handR'
  | 'hipL' | 'kneeL' | 'ankleL' | 'toeL'
  | 'hipR' | 'kneeR' | 'ankleR' | 'toeR';

export type Skeleton = Record<JointName, Vec3>;

/** Material ids are indices into this list; groups are named by it. */
export const MATERIAL_NAMES = Object.keys(SPEC.materials);
export const MAT: Record<string, number> = Object.fromEntries(
  MATERIAL_NAMES.map((k, i) => [k, i]),
);

export function buildSkeleton(s: Spec = SPEC): Skeleton {
  const L = s.landmarks;
  const w = s.widths;
  const p = s.pose;

  // Arms hang in a relaxed A-pose: abducted from the shoulder, carried a little
  // forward of the torso, with the elbow slightly out.  Lengths come from the
  // landmark heights so a change to `shoulder` or `crotch` carries through.
  const shoulderY = L.shoulder - p.shoulderDrop;
  const armSpan = shoulderY - L.crotch;
  // Measured on clay_2: the reference's fingertips stop being a separate
  // silhouette run at about y = 0.82; at 0.47/0.44 of the shoulder-to-crotch
  // span they stopped at 0.87, so the arm was ~5 cm short.
  const upperArm = armSpan * 0.50;
  const foreArm = armSpan * 0.47;

  const shoulderX = w.shoulderHalfW;
  const elbowX = shoulderX + upperArm * Math.sin(p.armAbduct);
  const elbowY = shoulderY - upperArm * Math.cos(p.armAbduct);
  const elbowZ = p.armForward + upperArm * 0.10;
  const wristX = elbowX + foreArm * Math.sin(p.armAbduct + p.elbowBend);
  const wristY = elbowY - foreArm * Math.cos(p.armAbduct + p.elbowBend);
  const wristZ = elbowZ + foreArm * 0.02;

  const hipX = w.hipHalfW * 0.52;
  const stance = p.stanceHalfW;
  const toe = Math.sin(p.footToeOut) * w.footLength;

  const opt = p as unknown as Record<string, number | undefined>;
  const lift = opt.footLift ?? 0;
  const fwd = opt.footForward ?? 0;
  const hipShift = opt.hipShift ?? 0;
  const pelvisTilt = opt.pelvisTilt ?? 0;
  const shoulderTilt = opt.shoulderTilt ?? 0;
  const hipY = L.crotch + (L.hip - L.crotch) * 0.45;
  const tiltL = shoulderTilt * w.shoulderHalfW;

  const mk = (x: number, y: number, z: number): Vec3 => [x, y, z];

  return {
    root: mk(0, 0, 0),
    hips: mk(0, L.hip, 0),
    waist: mk(0, L.waist, s.pose.spineLean * 0.5),
    chest: mk(0, L.bust, s.pose.spineLean),
    neck: mk(0, L.neckBase, s.pose.spineLean * 0.8),
    head: mk(0, (L.chin + L.crown) / 2, 0.004),
    headTop: mk(0, L.crown, 0.004),

    // Shoulders counter-rotate against the pelvis, which is what makes a
    // contrapposto read as a stance rather than as a broken rig.
    shoulderL: mk(shoulderX, shoulderY + tiltL, p.armForward),
    elbowL: mk(elbowX, elbowY + tiltL, elbowZ),
    wristL: mk(wristX, wristY + tiltL, wristZ),
    handL: mk(wristX + w.handLength * 0.30, wristY + tiltL - w.handLength * 0.86, wristZ),

    shoulderR: mk(-shoulderX, shoulderY - tiltL, p.armForward),
    elbowR: mk(-elbowX, elbowY - tiltL, elbowZ),
    wristR: mk(-wristX, wristY - tiltL, wristZ),
    handR: mk(-(wristX + w.handLength * 0.30), wristY - tiltL - w.handLength * 0.86, wristZ),

    // `landmarks.ankle` is the *visible* ankle on the outside of the boot, which
    // is what the boot author places a cuff against.  The skeleton needs the
    // anatomical joint, and the foot stands on top of the boot's sole slab
    // rather than on the floor -- getting this wrong leaves the foot as a
    // detached blob under the shin.
    //
    // The stance is a contrapposto, not a symmetric one.  Her left foot's
    // lowest pixel measures 0.047 m above her right's on clay_2, so the weight
    // is on the right leg and the left is raised and carried forward.  A
    // symmetric skeleton cannot match this turnaround at all: the two side
    // panels are genuinely different shapes (the reference's own mirror IoU is
    // 0.65), while an orthographic render of a symmetric model produces two
    // exactly mirrored silhouettes, so at best one of the two views can fit.
    hipL: mk(hipX + hipShift, hipY + pelvisTilt * hipX, 0),
    kneeL: mk(stance + hipShift * 0.5, L.knee + lift * 0.35, 0.006 + fwd * 0.35),
    ankleL: mk(stance + hipShift * 0.2, L.ankleJoint + lift, -0.012 + fwd),
    toeL: mk(stance + toe, L.footBed + 0.014 + lift, w.footLength * 0.78 + fwd),

    hipR: mk(-hipX + hipShift, hipY - pelvisTilt * hipX, 0),
    kneeR: mk(-stance + hipShift * 0.5, L.knee, 0.006),
    ankleR: mk(-stance + hipShift * 0.2, L.ankleJoint, -0.012),
    toeR: mk(-(stance + toe), L.footBed + 0.014, w.footLength * 0.78),
  };
}

/** Linear interpolation between two joints, for hanging things off a limb. */
export function along(a: Vec3, b: Vec3, t: number): Vec3 {
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t];
}

/** Mirror a point to the other side of the body. */
export function flipX(p: Vec3): Vec3 {
  return [-p[0], p[1], p[2]];
}

/**
 * Body radius at a given height, interpolated through the measured landmarks.
 * Clothing parts use it to sit just off the skin without re-deriving the torso.
 */
export function torsoHalfWidth(y: number, s: Spec = SPEC): { x: number; z: number } {
  const L = s.landmarks, w = s.widths;
  const keys: [number, number, number][] = [
    [L.crotch, w.hipHalfW * 0.86, w.hipHalfD * 0.90],
    [L.hip, w.hipHalfW, w.hipHalfD],
    [L.iliac, w.iliacHalfW, w.hipHalfD * 0.82],
    [L.waist, w.waistHalfW, w.waistHalfD],
    [L.underBust, w.chestHalfW * 0.94, w.chestHalfD * 0.94],
    [L.bust, w.bustHalfW, w.bustHalfD],
    [L.shoulder, w.chestHalfW, w.chestHalfD * 0.92],
    [L.neckBase, w.neckR * 1.9, w.neckR * 1.9],
  ];
  if (y <= keys[0][0]) return { x: keys[0][1], z: keys[0][2] };
  const last = keys[keys.length - 1];
  if (y >= last[0]) return { x: last[1], z: last[2] };
  for (let i = 1; i < keys.length; i++) {
    if (y <= keys[i][0]) {
      const [y0, x0, z0] = keys[i - 1];
      const [y1, x1, z1] = keys[i];
      const t = (y - y0) / Math.max(1e-6, y1 - y0);
      const s2 = t * t * (3 - 2 * t);
      return { x: x0 + (x1 - x0) * s2, z: z0 + (z1 - z0) * s2 };
    }
  }
  return { x: last[1], z: last[2] };
}
